### ISSUE TITLE
Move to another repository

### ISSUE THREAD

**Issue by gwik** [gwik/geventhttpclient#95]
I'm tend to move geventhttpclient to another repository that I don't own. As well as the release management.
I'm more a bottleneck than I add value to the project anymore.

Would you like it ?
Who would like to maintain it ?

cc @NorthIsUp @ml31415 @heyman @rmohr

**Comment by ml31415** [comment]
@heyman seems to actively use and rely on geventhttpclient with his project https://github.com/locustio/locust , so I guess he might have the strongest incentives to keep geventhttpclient alive and kickin. So I guess he might be the best choice.

**Comment by ml31415** [comment]
I guess who owns the github package is not that important and it's totally fine with staying yours. The more important thing would be pypi access to get some new master shipped now and then.

**Comment by NorthIsUp** [comment]
I haven't used the package in a while and would be a bad maintainer.

**Comment by cyberw** [comment]
Hi @gwik ! (another locust maintainer here)

For us, I think it doesnt really matter owns the repo, but it is problematic that there are no releases to pypi. Could you share the pypi project permissions with someone, or (even better) put a pypi access token (TWINE_USERNAME and TWINE_PASSWORD) in travis so that it can automatically be uploaded on tagged commits or something. see https://github.com/locustio/locust/blob/master/.travis.yml for an example of how it can work

**Comment by gwik** [comment]
Sorry for the late reply, automating pypi deployment seems a very
good idea, I'll try to set it up so I'm not longer retaining releases.

**Comment by cyberw** [comment]
@gwik Any progress? :)

**Comment by cyberw** [comment]
@gwik Ping! :)

**Comment by cyberw** [comment]
@gwik pretty please with sugar on top? :)

**Comment by gwik** [comment]
@cyberw it's pretty shaky but somehow it worked and 1.4.0 was released on the CI. I leave you guys the care of fixing the travis build. I'm completely outdated on the subject.
Sorry for the long wait. I can also add maintainers on pypi if needed.

**Comment by cyberw** [comment]
Awesome! If you want to add me, I’m ”cyberwiz” on pypi.

**Comment by gwik** [comment]
Done.
